### ISSUE TITLE
Open error report with kicad5.1.9

### ISSUE THREAD

**Issue by apple524** [UlfWetzker/game-and-watch-swd-implant#2]
open  swd_implant.kicad_pcb error。
![image](https://user-images.githubusercontent.com/44286181/113654436-6101cc00-96ca-11eb-904f-72e0aebd9124.png)

**Comment by wesk1** [comment]
getting similar message with latest kicad, any suggestions?

**Comment by UlfWetzker** [comment]
I use 6.0.0rc1 which is also available as flatpak.
Try a beta version or a nighly build, then it should work.
